# OPUS_FOUND - system has the OPUS library
# OPUS_INCLUDE_DIR - the OPUS include directory
# OPUS_LIBRARIES - The libraries needed to use OPUS

if (OPUS_INCLUDE_DIR AND OPUS_LIBRARIES)
	# in cache already
	SET(OPUS_FOUND TRUE)
else (OPUS_INCLUDE_DIR AND OPUS_LIBRARIES)
	FIND_PATH(OPUS_INCLUDE_DIR NAMES opus/opus.h)

	FIND_LIBRARY(OPUS_LIBRARIES NAMES opus)

	if (OPUS_INCLUDE_DIR AND OPUS_LIBRARIES)
		 set(OPUS_FOUND TRUE)
	endif (OPUS_INCLUDE_DIR AND OPUS_LIBRARIES)

	if (OPUS_FOUND)
		 if (NOT OPUS_FIND_QUIETLY)
				message(STATUS "Found OPUS: ${OPUS_LIBRARIES}")
		 endif (NOT OPUS_FIND_QUIETLY)
	else (OPUS_FOUND)
		 if (OPUS_FIND_REQUIRED)
				message(FATAL_ERROR "Could NOT find OPUS")
         else()
				message(STATUS "Could NOT find OPUS")
		 endif (OPUS_FIND_REQUIRED)
	endif (OPUS_FOUND)

#	MARK_AS_ADVANCED(OPUS_INCLUDE_DIR OPUS_LIBRARIES)
endif (OPUS_INCLUDE_DIR AND OPUS_LIBRARIES)
